import React, { useState, useEffect, useCallback, useRef } from "react";
import {
  analyzeSymptoms,
  generateSDXLImage,
  searchDrug,
} from "../../services/api";
import {
  Send,
  Sparkles,
  Loader2,
  Heart,
  AlertTriangle,
  ShieldCheck,
  UserCheck,
  Camera,
  X,
  MapPin,
  History,
  Trash2,
  RefreshCw,
  Pill,
  ChevronDown,
  ChevronUp,
  Search,
  Info,
  Mic,
  MicOff,
} from "lucide-react";
import {
  startListening,
  stopListening,
  isRecognitionSupported,
} from "../../services/speechService";

const BACKEND =
  import.meta.env.VITE_API_URL?.replace("/api", "") || "http://localhost:8000";

/**
 * InlineStepCard – renders one first-aid step with an AI image beside it.
 *
 * Strategy (in priority order):
 *  1. If step.image_url is already set by the backend analyze endpoint
 *     (a path like /api/analyze/image-file/{hash}), resolve it to a full
 *     URL and display it immediately — no extra network call needed.
 *  2. If step.image_url is missing or fails, fall back to calling
 *     /api/image-gen/generate (which proxies Pollinations internally).
 *     Requests are staggered by step number to avoid 429 rate limits.
 */
const InlineStepCard = ({ step, condition }) => {
  const [imgSrc, setImgSrc] = useState(null);
  const [busy, setBusy] = useState(false);
  const [errMsg, setErrMsg] = useState(null);
  const hasFetched = useRef(false);

  // Resolve the backend-provided image URL to a full absolute URL
  const resolveBackendUrl = (url) => {
    if (!url) return null;
    if (url.startsWith("http")) return url; // Already absolute
    if (url.startsWith("/api/") || url.startsWith("/api")) {
      return `${BACKEND}${url}`; // Relative backend path
    }
    return url;
  };

  const fetchViaGenerateApi = useCallback(async () => {
    if (busy) return;
    setBusy(true);
    setErrMsg(null);
    setImgSrc(null);

    const prompt =
      `3D animated educational medical illustration. ` +
      `Show a person correctly performing this first aid action: ${step.step_text}. ` +
      `Pixar style. Healthcare training animation. Bright colors. ` +
      `Clear action demonstration. No text overlay. High quality.`;

    console.log(
      `[InlineStepCard] Step ${step.step_number}: calling /api/image-gen/generate…`,
    );

    // Stagger: each step waits (step_number-1) * 1.2s to avoid 429 rate limits
    const delay = (step.step_number - 1) * 1200;
    if (delay > 0) await new Promise((r) => setTimeout(r, delay));

    try {
      const data = await generateSDXLImage(prompt);
      console.log(
        `[InlineStepCard] Step ${step.step_number}: OK — length=${data.image_url?.length ?? 0}`,
      );
      if (!data.image_url) throw new Error("Backend returned empty image_url");
      setImgSrc(data.image_url);
    } catch (e) {
      const msg =
        e?.response?.data?.detail || e?.message || "Generation failed";
      console.error(`[InlineStepCard] Step ${step.step_number} error:`, msg);
      setErrMsg(msg);
    } finally {
      setBusy(false);
    }
  }, [step.step_text, step.step_number]);

  useEffect(() => {
    if (hasFetched.current) return;
    hasFetched.current = true;

    const prebuilt = resolveBackendUrl(step.image_url);
    if (prebuilt) {
      // Path 1: use the image already generated by the analyze endpoint
      console.log(
        `[InlineStepCard] Step ${step.step_number}: using pre-built URL: ${prebuilt.slice(0, 80)}`,
      );
      setImgSrc(prebuilt);
    } else {
      // Path 2: no pre-built image, call /api/image-gen/generate
      fetchViaGenerateApi();
    }
  }, []);

  const handleRetry = useCallback(() => {
    hasFetched.current = false;
    setErrMsg(null);
    setImgSrc(null);
    setBusy(false);
    // Small delay so React re-renders before we start
    setTimeout(() => {
      hasFetched.current = true;
      fetchViaGenerateApi();
    }, 100);
  }, [fetchViaGenerateApi]);

  return (
    <div className="flex flex-col sm:flex-row items-stretch sm:items-start gap-4 p-4 rounded-xl bg-slate-950/30 border border-slate-800/50 hover:border-slate-700/60 transition-all duration-200">
      {/* Step number badge */}
      <div className="shrink-0 flex items-center gap-2 sm:block">
        <div className="w-8 h-8 rounded-full bg-blue-600/15 border border-blue-500/30 flex items-center justify-center">
          <span className="text-xs font-extrabold text-blue-400">
            {step.step_number}
          </span>
        </div>
        <span className="sm:hidden text-xs font-bold text-slate-400">
          Step {step.step_number}
        </span>
      </div>

      {/* Image area */}
      <div className="w-full sm:w-64 h-44 sm:h-40 rounded-lg overflow-hidden border border-slate-800/60 bg-slate-950 flex items-center justify-center relative shrink-0 group">
        {/* Loading spinner */}
        {busy && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-1.5 bg-slate-950 z-10">
            <div className="w-6 h-6 rounded-full border-2 border-violet-500/30 border-t-violet-400 animate-spin" />
            <p className="text-[9px] text-slate-500 font-bold">Generating…</p>
          </div>
        )}

        {/* Error state */}
        {errMsg && !busy && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-1.5 z-10 bg-slate-950 p-2">
            <p className="text-[9px] text-rose-450 text-center leading-tight line-clamp-2">
              {errMsg.length > 40 ? "Generation failed" : errMsg}
            </p>
            <button
              onClick={handleRetry}
              className="text-[9px] text-rose-450 hover:text-rose-350 flex items-center gap-0.5 font-bold mt-1"
            >
              <RefreshCw className="h-3 w-3 animate-spin-hover" /> Retry
            </button>
          </div>
        )}

        {/* Loaded image */}
        {imgSrc && !busy && (
          <img
            src={imgSrc}
            alt={`First aid step ${step.step_number}`}
            className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
            onLoad={() => {
              console.log(
                `[InlineStepCard] Step ${step.step_number}: image rendered ✓`,
              );
            }}
            onError={(e) => {
              console.warn(
                `[InlineStepCard] Step ${step.step_number}: img onError — falling back to generate API`,
              );
              e.target.style.display = "none";
              setImgSrc(null);
              // If the pre-built URL failed, fall back to the generate API
              if (!errMsg) fetchViaGenerateApi();
            }}
          />
        )}
      </div>

      {/* Step text */}
      <div className="flex-1 min-w-0 pt-0.5">
        <p className="text-[14px] sm:text-base text-slate-100 font-semibold leading-relaxed">
          {step.step_text}
        </p>
      </div>
    </div>
  );
};

// ─────────────────────────────────────────────────────────────────────────────
// Compact expandable drug card
// ─────────────────────────────────────────────────────────────────────────────
const DrugMiniCard = ({ drug }) => {
  const [open, setOpen] = useState(false);
  return (
    <div className="bg-slate-950/50 border border-slate-800/60 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((p) => !p)}
        className="w-full flex items-start gap-3 px-4 py-3 text-left hover:bg-slate-900/40 transition-colors cursor-pointer"
      >
        <div className="flex-1 min-w-0">
          <p className="text-xs font-extrabold text-slate-100 truncate">
            {drug.brand_name}
          </p>
          {drug.generic_name !== drug.brand_name &&
            drug.generic_name !== "Not available" && (
              <p className="text-[10px] text-slate-500 truncate">
                {drug.generic_name}
              </p>
            )}
          {drug.route !== "Not available" && (
            <span className="mt-1 inline-block text-[9px] bg-purple-500/10 text-purple-400 border border-purple-500/20 px-1.5 py-0.5 rounded-full font-bold">
              {drug.route}
            </span>
          )}
        </div>
        {open ? (
          <ChevronUp className="h-3.5 w-3.5 text-slate-500 shrink-0 mt-0.5" />
        ) : (
          <ChevronDown className="h-3.5 w-3.5 text-slate-500 shrink-0 mt-0.5" />
        )}
      </button>

      {open && (
        <div className="px-4 pb-4 flex flex-col gap-2 border-t border-slate-800/40">
          {drug.indications !== "Not available" && (
            <div className="pt-2">
              <p className="text-[9px] text-slate-500 font-bold uppercase tracking-wider mb-1">
                Uses / Indications
              </p>
              <p className="text-[11px] text-slate-300 leading-relaxed line-clamp-4">
                {drug.indications}
              </p>
            </div>
          )}
          {drug.dosage !== "Not available" && (
            <div>
              <p className="text-[9px] text-blue-400 font-bold uppercase tracking-wider mb-1">
                Dosage
              </p>
              <p className="text-[11px] text-slate-300 leading-relaxed line-clamp-3">
                {drug.dosage}
              </p>
            </div>
          )}
          {drug.warnings !== "Not available" && (
            <div className="bg-amber-50 border border-amber-250/80 rounded-lg p-2.5 mt-1">
              <p className="text-[10px] text-amber-800 font-extrabold uppercase tracking-wider mb-1 flex items-center gap-1.5">
                <AlertTriangle className="h-3.5 w-3.5 text-amber-600 shrink-0" />{" "}
                Warnings
              </p>
              <p className="text-[11px] text-amber-950 leading-relaxed font-semibold">
                {drug.warnings}
              </p>
            </div>
          )}
          {drug.side_effects !== "Not available" && (
            <div>
              <p className="text-[9px] text-slate-500 font-bold uppercase tracking-wider mb-1">
                Side Effects
              </p>
              <p className="text-[11px] text-slate-400 leading-relaxed line-clamp-3">
                {drug.side_effects}
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// ─────────────────────────────────────────────────────────────────────────────
// DrugInfoPanel – auto-searches OpenFDA for drugs related to the condition
// ─────────────────────────────────────────────────────────────────────────────
const DrugInfoPanel = ({ condition }) => {
  const [drugs, setDrugs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [manualQuery, setManualQuery] = useState("");
  const lastCondition = useRef(null);

  // Map condition keywords to relevant drug names for OpenFDA search
  const extractDrugKeyword = (cond) => {
    if (!cond) return "";
    const map = {
      burn: "silver sulfadiazine",
      fracture: "ibuprofen",
      fever: "acetaminophen",
      headache: "ibuprofen",
      allergy: "diphenhydramine",
      asthma: "albuterol",
      diabetes: "metformin",
      hypertension: "amlodipine",
      infection: "amoxicillin",
      pain: "ibuprofen",
      wound: "povidone iodine",
      seizure: "diazepam",
      heart: "aspirin",
      angina: "nitroglycerin",
      stroke: "aspirin",
      anaphylaxis: "epinephrine",
      shock: "epinephrine",
      sprain: "ibuprofen",
      nausea: "ondansetron",
      vomiting: "ondansetron",
      diarrhea: "loperamide",
      anxiety: "lorazepam",
      snake: "antivenom",
      poison: "activated charcoal",
      bleeding: "tranexamic acid",
      inflammation: "ibuprofen",
      cold: "cetirizine",
      cough: "dextromethorphan",
      chest: "aspirin",
      choking: "oxygen",
    };
    const lower = cond.toLowerCase();
    for (const [key, drug] of Object.entries(map)) {
      if (lower.includes(key)) return drug;
    }
    return lower.split(/[\s,/(]+/)[0] || cond;
  };

  const doSearch = async (query) => {
    if (!query || query.length < 2) return;
    setLoading(true);
    setSearched(true);
    setDrugs([]);
    try {
      const data = await searchDrug(query, 4);
      setDrugs(data.results || []);
    } catch {
      setDrugs([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!condition || condition === lastCondition.current) return;
    lastCondition.current = condition;
    const kw = extractDrugKeyword(condition);
    setSearchTerm(kw);
    setManualQuery(kw);
    doSearch(kw);
  }, [condition]);

  const handleManualSearch = (e) => {
    e.preventDefault();
    if (manualQuery.trim().length >= 2) doSearch(manualQuery.trim());
  };

  return (
    <div className="glass-card p-5 rounded-xl border-l-4 border-l-purple-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 flex flex-col gap-4 animate-fadeIn">
      <div className="flex items-center gap-2 border-b border-slate-800/60 pb-3">
        <Pill className="h-4.5 w-4.5 text-purple-600" />
        <h3 className="text-xs font-black text-slate-100 uppercase tracking-wider">
          Drug Information
        </h3>
        <span className="ml-auto text-[9px] font-black text-slate-400 uppercase tracking-wider">
          via OpenFDA
        </span>
      </div>

      <form onSubmit={handleManualSearch} className="flex gap-2">
        <div className="relative flex-1">
          <input
            type="text"
            value={manualQuery}
            onChange={(e) => setManualQuery(e.target.value)}
            placeholder="Search drug name…"
            className="w-full bg-slate-950/60 border border-slate-800 rounded-lg pl-8 pr-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-purple-500/60 transition-colors placeholder:text-slate-600"
          />
          <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-slate-500" />
        </div>
        <button
          type="submit"
          disabled={loading || manualQuery.trim().length < 2}
          className="bg-purple-600/80 hover:bg-purple-500 text-white px-3 py-2 rounded-lg text-xs font-bold transition-all disabled:opacity-40 flex items-center gap-1.5 cursor-pointer"
        >
          {loading ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Search className="h-3.5 w-3.5" />
          )}
        </button>
      </form>

      {searchTerm && !loading && (
        <p className="text-[10px] text-slate-500 -mt-2">
          Auto-searched:{" "}
          <span className="text-purple-400 font-semibold">{searchTerm}</span>
        </p>
      )}

      {loading && (
        <div className="flex items-center justify-center gap-2 py-6 text-slate-500">
          <Loader2 className="h-4 w-4 animate-spin text-purple-400" />
          <span className="text-xs">Searching FDA database…</span>
        </div>
      )}

      {!loading && drugs.length > 0 && (
        <div className="flex flex-col gap-3">
          {drugs.map((drug, i) => (
            <DrugMiniCard key={i} drug={drug} />
          ))}
        </div>
      )}

      {!loading && searched && drugs.length === 0 && (
        <div className="flex items-center gap-2 text-slate-500 py-3 text-xs">
          <Info className="h-4 w-4 shrink-0" />
          No FDA drug found for "{searchTerm}". Try a generic drug name above.
        </div>
      )}

      {!loading && !searched && (
        <div className="flex items-center gap-2 text-slate-600 text-xs py-2">
          <Pill className="h-4 w-4 shrink-0 opacity-40" />
          Drug info appears automatically after analysis.
        </div>
      )}
    </div>
  );
};

const AnalyzerChat = ({
  setActiveTab,
  initialQuery = "",
  setInitialQuery,
  initialImage = null,
  setInitialImage,
  initialImagePreview = null,
  setInitialImagePreview,
}) => {
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  // Voice input (Web Speech API)
  const [voiceActive, setVoiceActive] = useState(false);
  const [interimText, setInterimText] = useState("");
  const [voiceError, setVoiceError] = useState(null);

  // Stop listening on unmount
  useEffect(() => {
    return () => {
      stopListening();
    };
  }, []);

  const handleVoiceToggle = () => {
    if (voiceActive) {
      stopListening();
      setVoiceActive(false);
      setInterimText("");
    } else {
      setVoiceError(null);
      setVoiceActive(true);
      startListening(
        (finalText) => {
          setQuery((prev) => (prev ? prev + " " + finalText : finalText));
          setVoiceActive(false);
          setInterimText("");
        },
        (interim) => setInterimText(interim),
        (err) => {
          setVoiceError(err);
          setVoiceActive(false);
          setInterimText("");
          setTimeout(() => setVoiceError(null), 4000);
        },
      );
    }
  };

  const parseFirstAidSteps = (firstAidText) => {
    if (!firstAidText) return { steps: [], notes: [] };

    const rawLines = firstAidText
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    const notes = [];
    const mainLines = [];

    rawLines.forEach((line) => {
      if (
        line.startsWith("⚠️") ||
        line.startsWith("⚡") ||
        line.startsWith("🚨") ||
        line.toLowerCase().startsWith("note:") ||
        line.toLowerCase().startsWith("disclaimer:") ||
        line.toLowerCase().startsWith("warning:")
      ) {
        notes.push(line);
      } else {
        mainLines.push(line);
      }
    });

    const mainText = mainLines.join(" ");
    const steps = [];

    // Split text using a lookahead for numbers 1-99 followed by dot/paren and not followed by another digit
    const stepRegex = /(?=\b\d{1,2}[\.\)](?!\d))/g;
    const parts = mainText
      .split(stepRegex)
      .map((p) => p.trim())
      .filter(Boolean);
    const hasNumberedParts = parts.some((part) => /^\d{1,2}[\.\)]/.test(part));

    if (hasNumberedParts) {
      parts.forEach((part) => {
        const match = part.match(/^(\d{1,2})[\.\)]\s*(.*)/s);
        if (match) {
          steps.push({
            num: parseInt(match[1]),
            text: match[2].trim(),
          });
        } else {
          if (steps.length > 0) {
            steps[steps.length - 1].text += " " + part;
          } else {
            notes.push(part);
          }
        }
      });
    } else {
      const sentenceRegex = /[^.!?]+[.!?]+(?=\s|$)/g;
      const sentences = mainText.match(sentenceRegex) || [mainText];

      let stepNum = 1;
      sentences.forEach((sentence) => {
        const cleanSentence = sentence.trim();
        if (cleanSentence) {
          steps.push({
            num: stepNum++,
            text: cleanSentence,
          });
        }
      });
    }

    steps.sort((a, b) => a.num - b.num);
    return { steps, notes };
  };

  const getCleanPrompt = (condition, stepText) => {
    const cleanCond = condition.replace(/\s*\(.*\)\s*/g, "").trim();
    const cleanStep = stepText.replace(/^\d+[\.\)]\s*/, "").trim();

    // Extract first 5 words to keep prompt concise
    const words = cleanStep.split(/\s+/);
    const shortStepText = words
      .slice(0, 5)
      .join(" ")
      .replace(/[^\w\s]/g, "")
      .trim();

    return `${cleanCond} first aid step: ${shortStepText}. medical procedure flat vector icon diagram, dark slate blue background, neon colors, professional clinical aesthetic`;
  };

  // Persistent recent queries state
  const [recentQueries, setRecentQueries] = useState(() => {
    try {
      const saved = localStorage.getItem("mediassist_recent_queries");
      return saved ? JSON.parse(saved) : [];
    } catch (err) {
      console.error("Failed to load recent queries:", err);
      return [];
    }
  });

  const saveQueriesToLocalStorage = (queries) => {
    try {
      localStorage.setItem(
        "mediassist_recent_queries",
        JSON.stringify(queries),
      );
    } catch (err) {
      console.warn(
        "Local storage write failed (likely quota exceeded), saving without base64 images:",
        err,
      );
      const cleanedQueries = queries.map((q, idx) => {
        if (idx > 0 && q.image) {
          return { ...q, image: null };
        }
        return q;
      });
      try {
        localStorage.setItem(
          "mediassist_recent_queries",
          JSON.stringify(cleanedQueries),
        );
      } catch (e) {
        const noImageQueries = queries.map((q) => ({ ...q, image: null }));
        localStorage.setItem(
          "mediassist_recent_queries",
          JSON.stringify(noImageQueries),
        );
      }
    }
  };

  const addQueryToRecent = (queryText, imageText, apiResult) => {
    if (!queryText && !imageText) return;

    const displayTitle = queryText?.trim() ? queryText : "Image Assessment";

    const newQuery = {
      id: Date.now().toString(),
      queryText: displayTitle,
      image: imageText,
      result: apiResult,
      timestamp: new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      }),
    };

    setRecentQueries((prev) => {
      const filtered = prev.filter(
        (q) => q.queryText.toLowerCase() !== displayTitle.toLowerCase(),
      );
      const updated = [newQuery, ...filtered].slice(0, 10);
      saveQueriesToLocalStorage(updated);
      return updated;
    });
  };

  const deleteQuery = (e, id) => {
    e.stopPropagation();
    setRecentQueries((prev) => {
      const updated = prev.filter((q) => q.id !== id);
      saveQueriesToLocalStorage(updated);
      return updated;
    });
  };

  const clearAllQueries = () => {
    setRecentQueries([]);
    localStorage.removeItem("mediassist_recent_queries");
  };

  const selectRecentQuery = (item) => {
    setResult(item.result);
    if (item.image) {
      setImagePreview(item.image);
      setImage(item.image);
    } else {
      setImagePreview(null);
      setImage(null);
    }
  };

  // Image attachments state
  const [image, setImage] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const fileInputRef = useRef(null);

  const processedInitialRef = useRef(null);

  useEffect(() => {
    if (initialQuery || initialImage) {
      const currentKey = `${initialQuery}_${initialImage ? initialImage.substring(0, 100) : ""}`;
      if (processedInitialRef.current === currentKey) {
        return;
      }
      processedInitialRef.current = currentKey;

      const q = initialQuery;
      const img = initialImage;
      const imgPrev = initialImagePreview;

      // Populate local state so it appears in the chat box
      setQuery(q);
      if (img) {
        setImage(img);
        setImagePreview(imgPrev);
      }

      // Clear the parent app states immediately to prevent duplicate runs
      if (setInitialQuery) setInitialQuery("");
      if (setInitialImage) setInitialImage(null);
      if (setInitialImagePreview) setInitialImagePreview(null);

      // Run analysis
      const triggerSubmission = async () => {
        setLoading(true);
        setError(null);
        try {
          const data = await analyzeSymptoms(
            q || "Image submitted for visual assessment.",
            img,
          );
          setResult(data);
          setError(null);
          addQueryToRecent(q, img, data);
        } catch (err) {
          console.error(err);
          setError(
            err.message || "Failed to analyze symptoms. Please try again.",
          );
        } finally {
          setLoading(false);
        }
      };

      triggerSubmission();
    }
  }, [
    initialQuery,
    initialImage,
    initialImagePreview,
    setInitialQuery,
    setInitialImage,
    setInitialImagePreview,
  ]);

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onloadend = () => {
      setImagePreview(reader.result);
      setImage(reader.result); // Base64 encoding
    };
    reader.readAsDataURL(file);
  };

  const handleRemoveImage = () => {
    setImage(null);
    setImagePreview(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!query.trim() && !image) return;

    setLoading(true);
    setError(null);
    const userMessage = query;
    const userImage = image;

    setQuery("");
    handleRemoveImage();

    try {
      const data = await analyzeSymptoms(
        userMessage || "Image submitted for visual assessment.",
        userImage,
      );
      setResult(data);
      setError(null);
      addQueryToRecent(userMessage, userImage, data);
    } catch (err) {
      console.error(err);
      setError(err.message || "Failed to analyze symptoms. Please try again.");
      // Restore the query so user can retry easily
      setQuery(userMessage);
    } finally {
      setLoading(false);
    }
  };

  const getSeverityStyles = (severity) => {
    switch (severity?.toLowerCase()) {
      case "low":
        return "bg-emerald-500/10 text-emerald-400 border-emerald-500/30";
      case "medium":
        return "bg-yellow-500/10 text-yellow-400 border-yellow-500/30";
      case "high":
        return "bg-orange-500/10 text-orange-400 border-orange-500/30";
      case "critical":
        return "bg-rose-500/10 text-rose-400 border-rose-500/30 animate-pulse";
      default:
        return "bg-slate-500/10 text-slate-400 border-slate-500/30";
    }
  };

  return (
    <div className="flex flex-col gap-5 w-full max-w-[1400px] mx-auto animate-fadeIn">
      {/* ── TOP: Analyzer Input Bar (centered, full-width) ─────────────────── */}
      <div className="glass-card p-5 rounded-2xl border border-slate-800/80 bg-slate-900/60 backdrop-blur-md">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-blue-600/20 p-2 rounded-xl border border-blue-500/20">
            <Sparkles className="h-5 w-5 text-blue-400" />
          </div>
          <div>
            <h2 className="text-base font-extrabold text-slate-100 tracking-tight">
              Multimodal Health Analyzer
            </h2>
            <p className="text-[11px] text-slate-400">
              Describe symptoms or snap a photo for real-time AI guidance
            </p>
          </div>
          {result && (
            <div className="ml-auto flex items-center gap-2">
              <span
                className={`text-xs px-3 py-1 rounded-full border font-bold ${getSeverityStyles(result.severity)}`}
              >
                {result.severity} Severity
              </span>
              <span className="text-xs font-extrabold text-slate-100">
                {result.condition}
              </span>
            </div>
          )}
        </div>

        <form onSubmit={handleSubmit}>
          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 sm:items-center">
            <div className="flex-1 flex items-center gap-2 sm:gap-3 bg-slate-950/60 border border-slate-800 rounded-xl px-3 sm:px-4 focus-within:border-blue-500/60 transition-all min-w-0">
              <input
                type="text"
                value={voiceActive ? interimText || query : query}
                onChange={(e) => !voiceActive && setQuery(e.target.value)}
                placeholder={
                  voiceActive
                    ? "🎙️ Listening… speak your symptoms"
                    : imagePreview
                      ? "Describe the condition in photo…"
                      : "e.g. My hand got burned, snake bite, chest pain…"
                }
                disabled={loading}
                readOnly={voiceActive}
                className={`flex-1 min-w-0 bg-transparent py-3 sm:py-4 text-sm sm:text-lg text-slate-200 focus:outline-none placeholder:text-slate-600 ${voiceActive ? "placeholder-violet-400" : ""}`}
              />
              {imagePreview && (
                <div className="relative shrink-0 py-2 sm:py-0">
                  <img
                    src={imagePreview}
                    alt="Preview"
                    className="h-8 w-8 sm:h-10 sm:w-10 object-cover rounded-lg"
                  />
                  <button
                    type="button"
                    onClick={handleRemoveImage}
                    className="absolute -top-1 -right-1 bg-rose-600 text-white p-0.5 rounded-full"
                  >
                    <X className="h-2.5 w-2.5" />
                  </button>
                </div>
              )}
            </div>

            <div className="flex gap-2 sm:gap-3">
              {isRecognitionSupported() && (
                <button
                  type="button"
                  id="analyzer-voice-input-btn"
                  onClick={handleVoiceToggle}
                  disabled={loading}
                  title={
                    voiceActive
                      ? "Stop recording"
                      : "Voice input — speak your symptoms"
                  }
                  className={`flex-1 sm:flex-none flex justify-center items-center p-3 sm:p-4 border rounded-xl transition-all duration-200 shrink-0 cursor-pointer ${
                    voiceActive
                      ? "bg-violet-600 text-white animate-pulse border-violet-500 shadow-lg shadow-violet-500/30"
                      : "bg-slate-900 border-slate-800 text-slate-400 hover:text-violet-400 hover:border-violet-500/40"
                  }`}
                >
                  {voiceActive ? (
                    <MicOff className="h-5 w-5 sm:h-5.5 sm:w-5.5" />
                  ) : (
                    <Mic className="h-5 w-5 sm:h-5.5 sm:w-5.5" />
                  )}
                </button>
              )}

              <input
                type="file"
                ref={fileInputRef}
                onChange={handleImageChange}
                accept="image/*"
                capture="environment"
                className="hidden"
              />
              <button
                type="button"
                onClick={() => fileInputRef.current.click()}
                disabled={loading}
                className="flex-1 sm:flex-none flex justify-center items-center p-3 sm:p-4 bg-slate-900 border border-slate-800 hover:border-blue-500/40 text-slate-400 hover:text-blue-400 rounded-xl transition-all"
              >
                <Camera className="h-5 w-5 sm:h-5.5 sm:w-5.5" />
              </button>
              <button
                type="submit"
                disabled={loading || (!query.trim() && !image)}
                className="flex-[2] sm:flex-none bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white rounded-xl px-4 py-3 sm:px-6 sm:py-4 flex justify-center items-center gap-2 sm:gap-2.5 font-bold text-sm sm:text-base transition-all"
              >
                {loading ? (
                  <Loader2 className="h-5 w-5 animate-spin shrink-0" />
                ) : (
                  <Send className="h-5 w-5 shrink-0" />
                )}
                {loading ? "Analyzing…" : "Analyze"}
              </button>
            </div>
          </div>
          {voiceError && (
            <div className="text-xs text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded-lg px-3 py-2 mt-2">
              {voiceError}
            </div>
          )}
        </form>
      </div>

      {/* ── MAIN 2-COLUMN GRID (70% Left, 30% Right) ─────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-[7fr_3fr] gap-6 items-start">
        {/* ── LEFT COLUMN: First Aid Steps (70% width) ────────────────────── */}
        <div className="min-w-0 flex flex-col gap-4">
          {result ? (
            <div className="flex flex-col gap-4 animate-fadeIn">
              {/* First Aid Steps – each step has SDXL image beside it */}
              {(() => {
                const { steps, notes } = parseFirstAidSteps(result.first_aid);
                const apiSteps =
                  result.step_images && result.step_images.length > 0
                    ? result.step_images
                    : steps.map((s) => ({
                        step_number: s.num,
                        step_text: s.text,
                      }));

                if (apiSteps.length === 0)
                  return (
                    <div className="glass-card p-5 rounded-xl border border-slate-800 text-xs text-slate-300 leading-relaxed whitespace-pre-line">
                      {result.first_aid}
                    </div>
                  );

                return (
                  <div className="glass-card p-6 rounded-2xl border-l-4 border-l-rose-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 flex flex-col gap-4 shadow-sm">
                    <div className="flex items-center justify-between border-b border-slate-800/60 pb-3 flex-wrap gap-2">
                      <div className="flex items-center gap-2">
                        <Heart className="h-4.5 w-4.5 text-rose-600 animate-pulse" />
                        <h3 className="text-xs font-black text-slate-100 uppercase tracking-wider">
                          First Aid Guidelines
                        </h3>
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider">
                          ({apiSteps.length} steps)
                        </span>
                      </div>

                      <button
                        onClick={() => setActiveTab && setActiveTab("hospitals")}
                        className="flex items-center gap-1.5 text-[10px] font-extrabold text-emerald-600 hover:text-emerald-500 bg-emerald-500/10 border border-emerald-500/25 px-2.5 py-1.5 rounded-lg transition-all cursor-pointer"
                      >
                        <MapPin className="h-3.5 w-3.5" /> Find Hospitals
                      </button>
                    </div>

                    {notes.length > 0 ? (
                      <div className="bg-amber-50 border border-amber-200 text-amber-950 px-3 py-2.5 rounded-lg text-[11px] flex flex-col gap-2 font-semibold shadow-sm">
                        <div className="flex items-start gap-2">
                          <span className="shrink-0 text-amber-600">⚠️</span>
                          <p className="leading-relaxed">{notes[0]}</p>
                        </div>
                        <div className="flex items-center gap-1.5 pt-1.5 border-t border-amber-200/40 text-[10px] text-blue-600 font-extrabold">
                          <span>🩺</span>
                          <span>Medical Specialist Recommended: <strong>{result.doctor_type}</strong></span>
                        </div>
                      </div>
                    ) : (
                      <div className="bg-blue-50/60 border border-blue-200/50 text-blue-950 px-3 py-2.5 rounded-lg text-[11px] flex items-center gap-2 font-semibold shadow-sm">
                        <span className="shrink-0 text-blue-600">🩺</span>
                        <p className="leading-relaxed">Medical Specialist Recommended: <strong className="text-blue-700 font-extrabold">{result.doctor_type}</strong></p>
                      </div>
                    )}

                    <div className="flex flex-col gap-3">
                      {apiSteps.map((step, idx) => (
                        <InlineStepCard
                          key={`${result.condition}-s${step.step_number}-${idx}`}
                          step={step}
                          condition={result.condition}
                        />
                      ))}
                    </div>
                  </div>
                );
              })()}
            </div>
          ) : error ? (
            <div className="glass-card p-8 rounded-xl border border-dashed border-rose-500/30 flex flex-col items-center justify-center text-center gap-4 animate-fadeIn">
              <div className="bg-rose-500/10 p-4 rounded-full border border-rose-500/20 text-rose-400">
                <AlertTriangle className="h-7 w-7" />
              </div>
              <div>
                <h3 className="text-base font-bold text-slate-100">
                  Analysis Failed
                </h3>
                <p className="text-xs text-slate-400 mt-1 max-w-xs">{error}</p>
              </div>
              <button
                onClick={() => setError(null)}
                className="bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs px-5 py-2.5 rounded-xl transition-colors"
              >
                Try Again
              </button>
            </div>
          ) : (
            <div className="glass-card p-10 rounded-xl border border-dashed border-slate-800 flex flex-col items-center justify-center text-center gap-4 animate-fadeIn">
              <div className="bg-slate-900 p-4 rounded-full border border-slate-800 text-slate-600">
                <ShieldCheck className="h-8 w-8" />
              </div>
              <div>
                <h3 className="text-base font-bold text-slate-100">
                  Awaiting Input
                </h3>
                <p className="text-xs text-slate-500 mt-1 max-w-xs">
                  Enter your symptoms above or upload a photo to get instant
                  AI-guided first aid.
                </p>
              </div>
            </div>
          )}
        </div>

        {/* ── RIGHT COLUMN: Sidebar (Diagnosis, Doctor, Hospitals, Drug Info, Recent, Helplines) ── */}
        <div className="flex flex-col gap-4 sticky top-4">
          {/* Diagnosis Banner (Moved here from Left Column, 30% width) */}
          {result && (
            <div className="glass-card px-5 py-4 rounded-xl border-l-4 border-l-cyan-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 relative overflow-hidden animate-fadeIn shadow-sm">
              <div className="absolute inset-0 bg-gradient-to-r from-cyan-600/5 via-transparent to-transparent" />
              <div className="relative flex flex-col gap-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-black text-cyan-600 uppercase tracking-wider">
                    Diagnosis
                  </span>
                  <span
                    className={`px-2.5 py-0.5 rounded-full border text-xxs font-black uppercase tracking-wider ${getSeverityStyles(result.severity)}`}
                  >
                    {result.severity}
                  </span>
                </div>
                <h2 className="text-lg font-black text-slate-100 mt-0.5 leading-snug">
                  {result.condition}
                </h2>
                {result.symptoms && result.symptoms.length > 0 && (
                  <div className="flex flex-wrap gap-1 mt-1">
                    {result.symptoms.map((s, i) => (
                      <span
                        key={i}
                        className="text-[9px] px-1.5 py-0.5 rounded bg-slate-800/80 border border-slate-700/60 text-slate-300 font-semibold"
                      >
                        {s}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* See a Doctor */}
          {result && (
            <div className="glass-card rounded-xl border-l-4 border-l-blue-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 p-3.5 flex items-center justify-between gap-3 animate-fadeIn shadow-sm">
              <div className="flex items-center gap-2 min-w-0">
                <UserCheck className="h-4.5 w-4.5 text-blue-600 shrink-0" />
                <span className="text-xs font-extrabold text-slate-100 uppercase tracking-wider truncate">
                  Consult Doctor
                </span>
              </div>
              <span className="text-xs font-black text-blue-600 bg-blue-500/10 border border-blue-500/20 px-2.5 py-1 rounded-lg shrink-0">
                {result.doctor_type}
              </span>
            </div>
          )}

          {/* Find Hospitals */}
          {result && (
            <div className="glass-card rounded-xl border-l-4 border-l-emerald-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 overflow-hidden animate-fadeIn shadow-sm">
              <div className="px-4 py-3 border-b border-slate-800/60 flex items-center gap-2">
                <MapPin className="h-4.5 w-4.5 text-emerald-600" />
                <span className="text-xs font-black text-slate-100 uppercase tracking-wider">
                  Find Nearby Clinics
                </span>
              </div>
              <div className="p-4 flex flex-col gap-3">
                <p className="text-xs text-slate-650 leading-relaxed font-medium">
                  Locate clinics, hospitals, and critical care centers near you
                  equipped for{" "}
                  <span className="text-slate-900 font-bold">
                    {result.doctor_type}
                  </span>{" "}
                  services.
                </p>
                <button
                  onClick={() => setActiveTab && setActiveTab("hospitals")}
                  className="w-full bg-emerald-600 hover:bg-emerald-555 text-white font-extrabold text-xs py-2.5 rounded-lg border border-emerald-600 shadow-md shadow-emerald-500/10 transition-all flex items-center justify-center gap-2 cursor-pointer"
                >
                  <MapPin className="h-3.5 w-3.5" /> Find Hospitals Now
                </button>
              </div>
            </div>
          )}

          {/* Drug Information (taking full sidebar width) */}
          {result && (
            <div className="animate-fadeIn">
              <DrugInfoPanel condition={result.condition} />
            </div>
          )}

          {/* Recent Analyses Panel */}
          <div className="glass-card p-4 rounded-xl border-l-4 border-l-indigo-500 border-y-slate-800 border-r-slate-800 bg-slate-900/50 flex flex-col gap-3 shadow-sm">
            <div className="flex items-center justify-between pb-1">
              <span className="text-xs font-black text-slate-150 uppercase tracking-wider flex items-center gap-1.5">
                <History className="h-3.5 w-3.5 text-indigo-600" /> Recent
                Analyses
              </span>
              {recentQueries.length > 0 && (
                <button
                  onClick={clearAllQueries}
                  className="text-[9px] text-rose-450 hover:text-rose-350 font-bold flex items-center gap-0.5 cursor-pointer"
                >
                  <Trash2 className="h-2.5 w-2.5" /> Clear
                </button>
              )}
            </div>

            {recentQueries.length === 0 ? (
              <div className="glass-card rounded-xl border border-dashed border-slate-800 p-5 flex flex-col items-center gap-2 text-center bg-slate-950/20">
                <Heart className="h-5 w-5 text-slate-700" />
                <p className="text-[10px] text-slate-500">No analyses yet</p>
              </div>
            ) : (
              <div className="flex flex-col gap-1.5 max-h-[300px] overflow-y-auto pr-0.5">
                {recentQueries.map((item) => (
                  <button
                    key={item.id}
                    onClick={() => selectRecentQuery(item)}
                    className={`w-full text-left rounded-xl px-3 py-2.5 border transition-all duration-200 flex flex-col gap-0.5 group ${
                      result?.condition === item.result?.condition
                        ? "bg-blue-600/10 border-blue-500/50 shadow-sm shadow-blue-500/10"
                        : "bg-slate-900/40 border-slate-800/60 hover:border-slate-700 hover:bg-slate-900/70"
                    }`}
                  >
                    <div className="flex items-center justify-between gap-1">
                      <span className="text-[11px] font-bold text-slate-200 truncate flex-1">
                        {item.result?.condition || item.queryText}
                      </span>
                      <div
                        role="button"
                        tabIndex={0}
                        onClick={(e) => deleteQuery(e, item.id)}
                        onKeyDown={(e) =>
                          e.key === "Enter" && deleteQuery(e, item.id)
                        }
                        className="opacity-0 group-hover:opacity-100 text-slate-500 hover:text-rose-400 transition-all p-0.5 rounded shrink-0 cursor-pointer"
                      >
                        <Trash2 className="h-2.5 w-2.5" />
                      </div>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <span
                        className={`text-[9px] px-1.5 py-0.5 rounded-full border font-bold capitalize ${getSeverityStyles(item.result?.severity)}`}
                      >
                        {item.result?.severity}
                      </span>
                      <span className="text-[9px] text-slate-500 truncate">
                        {item.queryText}
                      </span>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Emergency Helplines (Always visible in sidebar) */}
          <div className="glass-card rounded-xl border border-rose-900/30 bg-rose-950/10 overflow-hidden">
            <div className="px-3 py-2 border-b border-rose-900/20 flex items-center gap-1.5">
              <AlertTriangle className="h-3.5 w-3.5 text-rose-400" />
              <span className="text-[10px] font-extrabold text-rose-300 uppercase tracking-wider">
                Emergency Helplines
              </span>
            </div>
            <div className="p-3 flex flex-col gap-1.5">
              {[
                { label: "All-in-One (DoT)", num: "112" },
                { label: "Ambulance", num: "108" },
                { label: "Police", num: "100" },
                { label: "Fire", num: "101" },
                { label: "Anti-Poison", num: "1066" },
                { label: "Women Distress", num: "1091" },
                { label: "Child Abuse", num: "1098" },
              ].map(({ label, num }) => (
                <a
                  key={num}
                  href={`tel:${num}`}
                  className="flex items-center justify-between group hover:bg-rose-950/30 px-1 py-0.5 rounded transition-colors"
                >
                  <span className="text-[10px] text-rose-300 font-bold">
                    {label}
                  </span>
                  <span className="text-sm font-extrabold text-white bg-rose-600 group-hover:bg-rose-500 px-2 py-0.5 rounded select-all transition-colors">
                    {num}
                  </span>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalyzerChat;
